import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";

const html = readFileSync("index.html", "utf8");
const css = readFileSync("styles.css", "utf8");
const js = readFileSync("src/main.js", "utf8");
const seedDestinationsPath = "src/data/seed-destinations.js";
const seedMemoriesPath = "src/data/seed-memories.js";

assert.match(html, /<script src="src\/main\.js"><\/script>/, "prototype should load the app through the src entry while keeping direct file-open support");
assert.match(html, /<script src="src\/data\/seed-destinations\.js"><\/script>\s*<script src="src\/data\/seed-memories\.js"><\/script>\s*<script src="src\/domain\/memory\.js"><\/script>\s*<script src="src\/storage\/local-store\.js"><\/script>\s*<script src="src\/storage\/archive-export\.js"><\/script>\s*<script src="src\/main\.js"><\/script>/, "seed, domain, storage, and transfer scripts should load before the app entry while keeping classic script support");
assert.equal(existsSync(seedDestinationsPath), true, "destination seed data should live in src/data");
assert.equal(existsSync(seedMemoriesPath), true, "memory seed data should live in src/data");

const seedDestinations = readFileSync(seedDestinationsPath, "utf8");
const seedMemories = readFileSync(seedMemoriesPath, "utf8");

assert.match(html, /data-screen="destination"/, "prototype should include a destination detail screen");
assert.match(html, /data-screen="archive"/, "prototype should include a full archive library screen");
assert.match(html, /data-open-archive/, "record home should expose an archive entry action");
assert.match(html, /data-archive-search/, "archive library should expose a search input");
assert.match(html, /data-archive-filter/, "archive library should expose filter controls");
assert.match(html, /data-archive-filter="favorite"/, "archive library should expose a favorite filter");
assert.match(html, /data-archive-filter="tagged"/, "archive library should expose a tagged filter");
assert.match(html, /data-archive-list/, "archive library should expose a dynamic result list");
assert.match(html, /data-archive-empty/, "archive library should expose an empty state");
assert.match(html, /data-export-archive/, "archive library should expose archive export");
assert.match(html, /data-import-archive/, "archive library should expose archive import");
assert.match(html, /data-edit-panel/, "archive library should expose an inline edit panel");
assert.match(html, /data-edit-title/, "archive edit panel should expose a title input");
assert.match(html, /data-edit-body/, "archive edit panel should expose a body input");
assert.match(html, /data-edit-location/, "archive edit panel should expose a location input");
assert.match(html, /data-edit-route/, "archive edit panel should expose a route input");
assert.match(html, /data-edit-photos/, "archive edit panel should expose photo URL editing");
assert.match(html, /data-edit-tags/, "archive edit panel should expose a tag input");
assert.match(html, /data-screen="memory-detail"/, "prototype should include a personal memory detail screen");
assert.match(html, /data-memory-back/, "memory detail should include a back action");
assert.match(html, /data-memory-title/, "memory detail should expose a title target");
assert.match(html, /data-memory-gallery/, "memory detail should expose a gallery target");
assert.match(html, /data-memory-route/, "memory detail should expose a route target");
assert.match(html, /data-destination-back/, "destination detail should include a back action");
assert.match(html, /data-destination-title/, "destination detail should expose a title target");
assert.match(html, /data-destination-score/, "destination detail should expose a score target");
assert.match(html, /data-review-card[^>]+data-destination-id=/, "review cards should link to destination detail data");
assert.match(html, /data-want-action/, "destination detail should include a want-to-go action");
assert.match(html, /data-plan-action/, "destination detail should include a planning action");
assert.match(html, /data-memory-action/, "destination detail should include a memory action");
assert.match(html, /data-plan-panel/, "destination detail should include a plan draft panel");
assert.match(html, /data-plan-title/, "plan draft should expose a destination title target");
assert.match(html, /data-plan-route/, "plan draft should expose a route target");
assert.match(html, /data-plan-status/, "plan draft should expose a status target");
assert.match(html, /data-create-title/, "create flow should expose a title input");
assert.match(html, /data-create-location/, "create flow should expose a location input");
assert.match(html, /data-create-body/, "create flow should expose a body input");
assert.match(html, /data-photo-option/, "create flow should include selectable photo assets");
assert.match(html, /data-selected-photos/, "create flow should render selected photos");
assert.match(html, /data-auto-timeline/, "create flow should render an automatic timeline");
assert.match(html, /data-share-poster/, "create flow should include a share poster preview");
assert.match(html, /data-generate-recap/, "create flow should expose a recap generation action");
assert.match(html, /data-photo-input/, "create flow should support local photo import");
assert.match(html, /data-import-photo/, "create flow should expose a photo import action");
assert.match(html, /data-export-canvas/, "create flow should include a canvas for PNG export");
assert.match(html, /data-download-poster/, "create flow should expose a poster download action");
assert.match(html, /data-save-memory/, "create flow should expose a save-to-archive action");
assert.match(html, /data-save-status/, "create flow should expose save feedback");
assert.match(html, /data-memory-row/, "record home should expose a dynamic memory row");
assert.match(html, /data-diary-timeline/, "record home should expose a dynamic diary timeline");
assert.match(html, /data-summary-memory/, "record home should expose an updatable memory count");

assert.match(css, /\.destination-screen/, "destination screen should have dedicated styling");
assert.match(css, /\.archive-screen/, "archive screen should have dedicated styling");
assert.match(css, /\.archive-search/, "archive search should be styled");
assert.match(css, /\.archive-filter-row/, "archive filters should be styled");
assert.match(css, /\.archive-list/, "archive list should be styled");
assert.match(css, /\.archive-actions/, "archive management actions should be styled");
assert.match(css, /\.tag-list/, "archive tags should be styled");
assert.match(css, /\.archive-transfer/, "archive import and export controls should be styled");
assert.match(css, /\.archive-edit-panel/, "archive edit panel should be styled");
assert.match(css, /\.memory-detail-screen/, "memory detail screen should have dedicated styling");
assert.match(css, /\.memory-detail-hero/, "memory detail hero should be styled");
assert.match(css, /\.memory-gallery/, "memory detail gallery should be styled");
assert.match(css, /\.destination-hero/, "destination hero should have dedicated styling");
assert.match(css, /\.insight-grid/, "destination insight metrics should be styled");
assert.match(css, /\.plan-draft/, "plan draft panel should be styled");
assert.match(css, /\.action-feedback/, "destination action feedback should be styled");
assert.match(css, /\.photo-option/, "selectable photo assets should be styled");
assert.match(css, /\.auto-timeline/, "automatic timeline should be styled");
assert.match(css, /\.share-poster/, "share poster should be styled");
assert.match(css, /\.selected-card/, "selected photos should expose ordering controls");
assert.match(css, /\.poster-export-actions/, "poster export actions should be styled");
assert.match(css, /\.save-memory-action/, "save-to-archive action should be styled");
assert.match(css, /\.save-status/, "save feedback should be styled");

assert.doesNotMatch(js, /const destinationData = \{/, "destination data should be extracted out of the app entry");
assert.doesNotMatch(js, /const seedMemories = \[/, "seed memories should be extracted out of the app entry");
assert.match(js, /window\.destinationData/, "app entry should read destination seed data from the classic-script global");
assert.match(js, /window\.seedMemories/, "app entry should read memory seed data from the classic-script global");
assert.match(js, /window\.shanhaiMemoryDomain/, "app entry should create user memories through the memory domain");
assert.match(seedDestinations, /window\.destinationData\s*=/, "destination seed data should be exposed for classic script loading");
assert.match(seedMemories, /window\.seedMemories\s*=/, "memory seed data should be exposed for classic script loading");
assert.match(js, /function openDestination/, "review card click should open a destination");
assert.match(js, /let activeArchiveFilter/, "archive library should track an active filter");
assert.match(js, /function openArchiveLibrary/, "archive entry action should open the archive library");
assert.match(js, /function renderArchiveLibrary/, "archive library should render archive entries");
assert.match(js, /function filterArchiveLibrary/, "archive library should filter entries");
assert.match(js, /function toggleArchiveFavorite/, "archive library should toggle favorites");
assert.match(js, /function deleteSavedMemory/, "archive library should delete saved entries");
assert.match(js, /function editSavedMemory/, "archive library should edit saved entries");
assert.match(js, /function saveEditedMemory/, "archive library should save inline edits");
assert.match(js, /function closeEditPanel/, "archive library should close inline edits");
assert.match(js, /function parsePhotoInput/, "archive library should parse edited photo URLs");
assert.match(js, /function inferLocationParts/, "archive library should update country and city from edited locations");
assert.doesNotMatch(js, /prompt\(/, "archive editing should not use browser prompt dialogs");
assert.match(js, /function exportArchive/, "archive library should export local archive JSON");
assert.match(js, /function importArchiveFile/, "archive library should import local archive JSON");
assert.match(js, /window\.shanhaiArchiveTransfer/, "app entry should use archive transfer helpers");
assert.match(js, /function openMemoryDetail/, "memory cards should open a personal memory detail");
assert.match(js, /function renderMemoryDetail/, "memory detail should render selected archive data");
assert.match(js, /function renderDestination/, "detail view should render selected destination data");
assert.match(js, /function toggleWantToGo/, "want-to-go action should be implemented");
assert.match(js, /function openPlanDraft/, "planning action should be implemented");
assert.match(js, /function openMemoryLink/, "memory action should be implemented");
assert.match(js, /window\.shanhaiLocalStore/, "destination actions should persist lightweight local state through the storage adapter");
assert.match(js, /function selectPhotoAsset/, "create flow should select photo assets");
assert.match(js, /function renderSelectedPhotos/, "create flow should render selected photos");
assert.match(js, /function renderAutoTimeline/, "create flow should render an automatic timeline");
assert.match(js, /function generateSharePoster/, "create flow should generate a share poster");
assert.match(js, /function importLocalPhotos/, "create flow should import local photo files");
assert.match(js, /function readFileAsDataUrl/, "local photo imports should convert files into persistent data URLs");
assert.match(js, /FileReader/, "local photo imports should use FileReader for refresh-safe persistence");
assert.doesNotMatch(js, /URL\.createObjectURL/, "saved local photos should not rely on temporary blob URLs");
assert.match(js, /function moveSelectedPhoto/, "create flow should reorder selected photos");
assert.match(js, /function drawPosterToCanvas/, "create flow should render poster PNG to canvas");
assert.match(js, /localStore\.persistSavedMemories/, "personal archive entries should use the storage adapter");
assert.match(js, /function saveCreatedMemory/, "create flow should save a memory entry");
assert.match(js, /function renderPersonalArchive/, "record home should render saved memory entries");
assert.match(js, /createForm\.addEventListener\("submit"/, "create form should intercept submit events");
assert.match(js, /event\.preventDefault\(\)/, "create form submit handling should prevent page reloads");
