import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";

const html = readFileSync("index.html", "utf8");
const css = readFileSync("styles.css", "utf8");
const js = readFileSync("src/main.js", "utf8");
const seedDestinationsPath = "src/data/seed-destinations.js";
const seedMemoriesPath = "src/data/seed-memories.js";

assert.match(html, /<script src="src\/main\.js\?v=profile-edit-3"><\/script>/, "prototype should load the app through the src entry while keeping direct file-open support");
assert.match(html, /<script src="src\/data\/seed-destinations\.js\?v=profile-edit-3"><\/script>\s*<script src="src\/data\/seed-memories\.js\?v=profile-edit-3"><\/script>\s*<script src="src\/domain\/memory\.js\?v=profile-edit-3"><\/script>\s*<script src="src\/storage\/local-store\.js\?v=profile-edit-3"><\/script>\s*<script src="src\/storage\/archive-export\.js\?v=profile-edit-3"><\/script>\s*<script src="src\/api-client\.js\?v=profile-edit-3"><\/script>\s*<script src="src\/main\.js\?v=profile-edit-3"><\/script>\s*<script src="src\/fullstack-panel\.js\?v=profile-edit-3"><\/script>/, "seed, domain, storage, API, app, and fullstack scripts should load in order while keeping classic script support");
assert.equal(existsSync(seedDestinationsPath), true, "destination seed data should live in src/data");
assert.equal(existsSync(seedMemoriesPath), true, "memory seed data should live in src/data");

const seedDestinations = readFileSync(seedDestinationsPath, "utf8");
const seedMemories = readFileSync(seedMemoriesPath, "utf8");

assert.match(html, /data-screen="destination"/, "prototype should include a destination detail screen");
assert.match(html, /data-screen="archive"/, "prototype should include a full archive library screen");
assert.match(html, /data-open-archive/, "record home should expose an archive entry action");
assert.match(html, /data-open-map-browse/, "record map should expose a browse action");
assert.match(html, /data-open-diary-browse/, "record diary should expose a browse action");
assert.match(html, /data-browse-panel/, "record should expose a browse panel");
assert.match(html, /data-browse-close/, "record browse panel should expose a close action");
assert.match(html, /data-archive-search/, "archive library should expose a search input");
assert.match(html, /data-archive-filter/, "archive library should expose filter controls");
assert.match(html, /data-archive-filter="favorite"/, "archive library should expose a favorite filter");
assert.match(html, /data-archive-filter="tagged"/, "archive library should expose a tagged filter");
assert.match(html, /data-archive-list/, "archive library should expose a dynamic result list");
assert.match(html, /data-archive-empty/, "archive library should expose an empty state");
assert.match(html, /data-export-archive/, "archive library should expose archive export");
assert.match(html, /data-import-archive/, "archive library should expose archive import");
assert.match(html, /data-edit-panel/, "archive library should expose an inline edit panel");
assert.match(html, /data-edit-title/, "archive edit panel should expose a title input");
assert.match(html, /data-edit-body/, "archive edit panel should expose a body input");
assert.match(html, /data-edit-location/, "archive edit panel should expose a location input");
assert.match(html, /data-edit-route/, "archive edit panel should expose a route input");
assert.match(html, /data-edit-photos/, "archive edit panel should expose photo URL editing");
assert.match(html, /data-edit-tags/, "archive edit panel should expose a tag input");
assert.match(html, /data-screen="memory-detail"/, "prototype should include a personal memory detail screen");
assert.match(html, /data-memory-back/, "memory detail should include a back action");
assert.match(html, /data-memory-title/, "memory detail should expose a title target");
assert.match(html, /data-memory-gallery/, "memory detail should expose a gallery target");
assert.match(html, /data-memory-route/, "memory detail should expose a route target");
assert.match(html, /data-destination-back/, "destination detail should include a back action");
assert.match(html, /data-destination-title/, "destination detail should expose a title target");
assert.match(html, /data-destination-score/, "destination detail should expose a score target");
assert.match(html, /data-review-card[^>]+data-destination-id=/, "review cards should link to destination detail data");
assert.match(html, /data-want-action/, "destination detail should include a want-to-go action");
assert.match(html, /data-plan-action/, "destination detail should include a planning action");
assert.match(html, /data-memory-action/, "destination detail should include a memory action");
assert.match(html, /data-plan-panel/, "destination detail should include a plan draft panel");
assert.match(html, /data-plan-title/, "plan draft should expose a destination title target");
assert.match(html, /data-plan-route/, "plan draft should expose a route target");
assert.match(html, /data-plan-status/, "plan draft should expose a status target");
assert.match(html, /data-create-title/, "create flow should expose a title input");
assert.match(html, /data-create-location/, "create flow should expose a location input");
assert.match(html, /data-create-body/, "create flow should expose a body input");
assert.match(html, /data-create-readiness/, "create flow should expose publishing readiness");
assert.match(html, /data-create-draft-state/, "create flow should expose draft save state");
assert.match(html, /data-create-photo-count/, "create flow should expose selected photo count");
assert.match(html, /data-create-publish-target/, "create flow should expose publish target");
assert.match(html, /data-photo-option/, "create flow should include selectable photo assets");
assert.match(html, /data-selected-photos/, "create flow should render selected photos");
assert.match(html, /data-auto-timeline/, "create flow should render an automatic timeline");
assert.match(html, /data-share-poster/, "create flow should include a share poster preview");
assert.match(html, /data-generate-recap/, "create flow should expose a recap generation action");
assert.match(html, /data-photo-input/, "create flow should support local photo import");
assert.match(html, /data-import-photo/, "create flow should expose a photo import action");
assert.match(html, /data-export-canvas/, "create flow should include a canvas for PNG export");
assert.match(html, /data-download-poster/, "create flow should expose a poster download action");
assert.match(html, /data-save-memory/, "create flow should expose a save-to-archive action");
assert.match(html, /data-save-status/, "create flow should expose save feedback");
assert.match(html, /data-memory-row/, "record home should expose a dynamic memory row");
assert.match(html, /data-diary-timeline/, "record home should expose a dynamic diary timeline");
assert.match(html, /data-summary-memory/, "record home should expose an updatable memory count");
assert.match(html, /data-cloud-panel/, "profile should expose a cloud account panel");
assert.match(html, /data-cloud-register/, "cloud account panel should expose registration");
assert.match(html, /data-cloud-login/, "cloud account panel should expose login");
assert.match(html, /data-cloud-save-memory/, "cloud account panel should create server-backed memories");
assert.match(html, /data-cloud-privacy/, "cloud account panel should choose private or public status");
assert.match(html, /data-cloud-photo-input/, "cloud account panel should upload photos");
assert.match(html, /data-cloud-photo-list/, "cloud account panel should manage uploaded photos");
assert.match(html, /data-cloud-delete-photo/, "cloud account panel should expose photo deletion");
assert.match(html, /data-cloud-update-profile/, "cloud account panel should expose profile updates");
assert.match(html, /data-cloud-delete-account/, "cloud account panel should expose account deletion");
assert.match(html, /data-public-memory-list/, "cloud account panel should show public published memories");
assert.match(html, /data-community-feed/, "community should expose a backend-driven discovery feed");
assert.match(html, /data-community-tab/, "community topic tabs should expose interactive data hooks");
assert.match(html, /data-community-panel/, "community topic tabs should control panels");
assert.match(html, /data-community-channel/, "community tabs should expose a visible active channel summary");
assert.doesNotMatch(html, /class="icon-button search-button"/, "community should not keep a redundant empty header search icon when search is already visible");
assert.match(html, /data-community-search-input/, "community should expose a discovery search input");
assert.match(html, /data-community-search-action/, "community should expose a discovery search action");
assert.match(html, /data-community-sort/, "community should expose discovery sorting");
assert.match(html, /data-community-like/, "community cards should expose like actions");
assert.match(html, /data-community-bookmark/, "community cards should expose bookmark actions");
assert.match(html, /data-community-comment-input/, "community cards should expose comment input");
assert.match(html, /data-community-comment-submit/, "community cards should expose comment submit actions");
assert.match(html, /data-community-follow/, "community cards should expose creator follow actions");
assert.match(html, /data-community-report/, "community cards should expose report actions");
assert.match(html, /data-creator-stats/, "cloud account panel should expose creator stats");
assert.match(html, /data-notification-list/, "messages should expose server notification list");
assert.match(html, /data-conversation-list/, "messages should expose friend conversations");
assert.match(html, /data-conversation-item/, "messages should expose selectable conversation items");
assert.match(html, /data-conversation-thread/, "messages should expose a friend conversation thread");
assert.match(html, /data-conversation-message-input/, "messages should expose a reply input");
assert.match(html, /data-message-inbox-summary/, "messages should expose an inbox summary");
assert.match(html, /data-message-unread-count/, "messages should expose unread conversation counts");
assert.match(html, /data-conversation-preview/, "conversation rows should expose mutable previews");
assert.match(html, /data-conversation-unread/, "conversation rows should expose read state");
assert.match(html, /data-message-thread-state/, "message thread should expose delivery state");
assert.match(html, /data-message-empty-reply/, "message thread should expose empty reply feedback");
assert.match(html, /data-profile-dashboard/, "profile should expose a structured dashboard");
assert.match(html, /data-profile-avatar-edit/, "profile avatar should open account and identity editing");
assert.match(html, /data-profile-avatar-image/, "profile should render a real avatar image");
assert.match(html, /data-screen="profile-space"/, "profile avatar and public-home entry should route to a personal space screen");
assert.match(html, /data-profile-space/, "personal space should expose a structured profile page");
assert.match(html, /data-open-profile-space/, "profile page should expose entry points into personal space");
assert.match(html, /data-profile-space-edit/, "personal space should expose an edit profile action");
assert.match(html, /data-profile-space-tab="comments"/, "personal space should expose a comments/interactions tab entry");
assert.match(html, /data-profile-edit-panel/, "profile should expose an avatar-driven edit panel");
assert.match(html, /data-profile-avatar-input/, "profile edit panel should support avatar upload preview");
assert.match(html, /data-profile-phone/, "profile edit panel should expose phone editing");
assert.match(html, /data-profile-bio/, "profile edit panel should expose bio editing");
assert.match(html, /data-cloud-photo-file-name/, "cloud photo upload should expose a styled file name display");
assert.doesNotMatch(html, /cloud-module cloud-account-module/, "account identity should not remain as a detached cloud module");
assert.match(html, /data-profile-primary-action/, "profile should expose primary actions");
assert.match(html, /data-profile-quick-action/, "profile should expose quick actions");
assert.match(html, /data-profile-account-state/, "profile dashboard should show the current account state");
assert.match(html, /data-profile-local-memories/, "profile dashboard should show local memory counts");
assert.match(html, /data-profile-public-memories/, "profile dashboard should show public memory counts");
assert.match(html, /data-profile-interactions/, "profile dashboard should show interaction counts");
assert.match(html, /data-profile-task-list/, "profile dashboard should expose a grouped app task list");
assert.doesNotMatch(html, /<strong>28<\/strong><span>映记<\/span>/, "profile dashboard should not show hard-coded archive stats");
assert.match(html, /<option value="unlisted">/, "cloud publishing should support unlisted visibility");

assert.match(css, /\.destination-screen/, "destination screen should have dedicated styling");
assert.match(css, /\.archive-screen/, "archive screen should have dedicated styling");
assert.match(css, /\.archive-search/, "archive search should be styled");
assert.match(css, /\.archive-filter-row/, "archive filters should be styled");
assert.match(css, /\.archive-list/, "archive list should be styled");
assert.match(css, /\.archive-actions/, "archive management actions should be styled");
assert.match(css, /\.tag-list/, "archive tags should be styled");
assert.match(css, /\.archive-transfer/, "archive import and export controls should be styled");
assert.match(css, /\.archive-edit-panel/, "archive edit panel should be styled");
assert.match(css, /\.memory-detail-screen/, "memory detail screen should have dedicated styling");
assert.match(css, /\.memory-detail-hero/, "memory detail hero should be styled");
assert.match(css, /\.memory-gallery/, "memory detail gallery should be styled");
assert.match(css, /\.destination-hero/, "destination hero should have dedicated styling");
assert.match(css, /\.insight-grid/, "destination insight metrics should be styled");
assert.match(css, /\.plan-draft/, "plan draft panel should be styled");
assert.match(css, /\.action-feedback/, "destination action feedback should be styled");
assert.match(css, /\.photo-option/, "selectable photo assets should be styled");
assert.match(css, /\.auto-timeline/, "automatic timeline should be styled");
assert.match(css, /\.share-poster/, "share poster should be styled");
assert.match(css, /\.selected-card/, "selected photos should expose ordering controls");
assert.match(css, /\.poster-export-actions/, "poster export actions should be styled");
assert.match(css, /\.save-memory-action/, "save-to-archive action should be styled");
assert.match(css, /\.save-status/, "save feedback should be styled");
assert.match(css, /\.cloud-panel/, "cloud account panel should be styled");
assert.match(css, /\.community-actions/, "community interaction actions should be styled");
assert.match(css, /\.community-channel-card/, "community tab active channel summary should be styled");
assert.match(css, /\.creator-stats/, "creator stats should be styled");
assert.match(css, /\.notification-list/, "notification list should be styled");
assert.match(css, /\.conversation-layout/, "friend conversation layout should be styled");
assert.match(css, /\.profile-dashboard/, "profile dashboard should be styled");
assert.match(css, /\.profile-space-screen/, "personal space screen should be styled");
assert.match(css, /\.profile-space-hero/, "personal space hero should be styled");
assert.match(css, /\.profile-space-tabs/, "personal space tabs should be styled");
assert.match(css, /\.profile-edit-panel/, "profile edit panel should be styled");
assert.match(css, /\.avatar-edit-badge/, "avatar edit affordance should be styled");
assert.match(css, /\.file-picker/, "cloud file picker should be styled");
assert.match(css, /\.cloud-danger-action/, "photo delete action should be styled");
assert.match(css, /\.public-memory-card/, "public memories should render as designed cards");
assert.match(css, /\.cloud-module/, "cloud account publishing should be styled as mobile product modules");
assert.match(css, /\.browse-panel/, "record browse panel should be styled");

assert.doesNotMatch(js, /const destinationData = \{/, "destination data should be extracted out of the app entry");
assert.doesNotMatch(js, /const seedMemories = \[/, "seed memories should be extracted out of the app entry");
assert.match(js, /window\.destinationData/, "app entry should read destination seed data from the classic-script global");
assert.match(js, /window\.seedMemories/, "app entry should read memory seed data from the classic-script global");
assert.match(js, /window\.shanhaiMemoryDomain/, "app entry should create user memories through the memory domain");
assert.match(seedDestinations, /window\.destinationData\s*=/, "destination seed data should be exposed for classic script loading");
assert.match(seedMemories, /window\.seedMemories\s*=/, "memory seed data should be exposed for classic script loading");
assert.match(js, /function openDestination/, "review card click should open a destination");
assert.match(js, /let activeArchiveFilter/, "archive library should track an active filter");
assert.match(js, /function openArchiveLibrary/, "archive entry action should open the archive library");
assert.match(js, /function renderArchiveLibrary/, "archive library should render archive entries");
assert.match(js, /function filterArchiveLibrary/, "archive library should filter entries");
assert.match(js, /function toggleArchiveFavorite/, "archive library should toggle favorites");
assert.match(js, /function deleteSavedMemory/, "archive library should delete saved entries");
assert.match(js, /function editSavedMemory/, "archive library should edit saved entries");
assert.match(js, /function saveEditedMemory/, "archive library should save inline edits");
assert.match(js, /function closeEditPanel/, "archive library should close inline edits");
assert.match(js, /function parsePhotoInput/, "archive library should parse edited photo URLs");
assert.match(js, /function inferLocationParts/, "archive library should update country and city from edited locations");
assert.doesNotMatch(js, /prompt\(/, "archive editing should not use browser prompt dialogs");
assert.match(js, /function exportArchive/, "archive library should export local archive JSON");
assert.match(js, /function importArchiveFile/, "archive library should import local archive JSON");
assert.match(js, /window\.shanhaiArchiveTransfer/, "app entry should use archive transfer helpers");
assert.match(js, /function openMemoryDetail/, "memory cards should open a personal memory detail");
assert.match(js, /function openRecordBrowse/, "record summary should open browse panels");
assert.match(js, /function switchCommunityTab/, "community topic tabs should switch panels");
assert.match(js, /function openConversation/, "messages should open friend conversations");
assert.match(js, /function sendConversationReply/, "messages should send local replies");
assert.match(js, /function renderMemoryDetail/, "memory detail should render selected archive data");
assert.match(js, /function renderDestination/, "detail view should render selected destination data");
assert.match(js, /function toggleWantToGo/, "want-to-go action should be implemented");
assert.match(js, /function openPlanDraft/, "planning action should be implemented");
assert.match(js, /function openMemoryLink/, "memory action should be implemented");
assert.match(js, /window\.shanhaiLocalStore/, "destination actions should persist lightweight local state through the storage adapter");
assert.match(js, /function selectPhotoAsset/, "create flow should select photo assets");
assert.match(js, /function renderSelectedPhotos/, "create flow should render selected photos");
assert.match(js, /function renderAutoTimeline/, "create flow should render an automatic timeline");
assert.match(js, /function generateSharePoster/, "create flow should generate a share poster");
assert.match(js, /function importLocalPhotos/, "create flow should import local photo files");
assert.match(js, /function readFileAsDataUrl/, "local photo imports should convert files into persistent data URLs");
assert.match(js, /FileReader/, "local photo imports should use FileReader for refresh-safe persistence");
assert.doesNotMatch(js, /URL\.createObjectURL/, "saved local photos should not rely on temporary blob URLs");
assert.match(js, /function moveSelectedPhoto/, "create flow should reorder selected photos");
assert.match(js, /function drawPosterToCanvas/, "create flow should render poster PNG to canvas");
assert.match(js, /localStore\.persistSavedMemories/, "personal archive entries should use the storage adapter");
assert.match(js, /function saveCreatedMemory/, "create flow should save a memory entry");
assert.match(js, /function renderPersonalArchive/, "record home should render saved memory entries");
assert.match(js, /createForm\.addEventListener\("submit"/, "create form should intercept submit events");
assert.match(js, /event\.preventDefault\(\)/, "create form submit handling should prevent page reloads");
const apiClient = readFileSync("src/api-client.js", "utf8");
const fullstackPanel = readFileSync("src/fullstack-panel.js", "utf8");
assert.match(apiClient, /discoverMemories/, "API client should expose community discovery");
assert.match(apiClient, /toggleLike/, "API client should expose likes");
assert.match(apiClient, /toggleBookmark/, "API client should expose bookmarks");
assert.match(apiClient, /createComment/, "API client should expose comments");
assert.match(apiClient, /followProfile/, "API client should expose follows");
assert.match(apiClient, /createReport/, "API client should expose reports");
assert.match(apiClient, /creatorStats/, "API client should expose creator stats");
assert.match(apiClient, /notifications/, "API client should expose notifications");
assert.match(apiClient, /updateMe/, "API client should expose profile updates");
assert.match(apiClient, /deleteMe/, "API client should expose account deletion");
assert.match(apiClient, /deletePhoto/, "API client should expose photo deletion");
assert.match(fullstackPanel, /renderCommunityFeed/, "fullstack panel should render backend community feed");
assert.match(fullstackPanel, /renderPhotoList/, "fullstack panel should render uploaded photo management");
assert.match(fullstackPanel, /renderCreatorStats/, "fullstack panel should render creator stats");
assert.match(fullstackPanel, /renderNotifications/, "fullstack panel should render notifications");
assert.match(fullstackPanel, /handleCommunityAction/, "fullstack panel should handle community actions");
